/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package app.alarms;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.io.UnsupportedEncodingException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author haywoosd
 */
public class AlarmsEntryPanel extends javax.swing.JPanel {

    private String timeText;
    private String nameText;
    private int entryNumber;

    /**
     * Creates new form AlarmsEntryPanel
     */
    public AlarmsEntryPanel(int hour, int minute, int period, String name, int number) {
        String hourText = String.valueOf(hour);
        String minuteText = String.valueOf(minute);
        String periodText;
        if (minuteText.length() < 2) {
            minuteText = "0" + minuteText;
        }
        if (period < 1) {
            periodText = "AM";
        } else {
            periodText = "PM";
        }
        nameText = name;
        timeText = hourText + ":" + minuteText + " " + periodText;
        entryNumber = number;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        timeLabel = new javax.swing.JLabel();
        removeButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(32767, 43));
        setMinimumSize(new java.awt.Dimension(0, 43));
        setName(""); // NOI18N
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(256, 43));

        timeLabel.setText(timeText);
        timeLabel.setToolTipText("");

        removeButton.setText("Remove");
        removeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText(nameText);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(timeLabel)
                .addGap(18, 18, 18)
                .addComponent(removeButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(timeLabel)
                    .addComponent(removeButton)
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void removeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeButtonActionPerformed
        setVisible(false);
        System.out.println("Removing alarm entry: " + nameText);
        AlarmsAlertThread.timerHours.remove(entryNumber);
        AlarmsAlertThread.timerMinutes.remove(entryNumber);
        AlarmsAlertThread.timerNames.remove(entryNumber);
        String newLine = System.getProperty("line.separator");
        try {
            File alarmsFile = new File(System.getProperty("user.home") + "\\AppData\\Roaming\\SuperToolkit\\Alarms.txt");
            FileInputStream input = new FileInputStream(alarmsFile);
            byte[] data = new byte[(int) alarmsFile.length()];
            input.read(data);
            input.close();
            String[] splitContent = new String(data, "UTF-8").split(newLine, -1);
            FileWriter alarmsWriter = new FileWriter(alarmsFile);
            for (int i = 0; i < (splitContent.length - 1) / 4; i++) {
                if (i == entryNumber) {
                    continue;
                } else {
                    alarmsWriter.write(splitContent[i * 4] + newLine);
                    alarmsWriter.write(splitContent[i * 4 + 1] + newLine);
                    alarmsWriter.write(splitContent[i * 4 + 2] + newLine);
                    alarmsWriter.write(splitContent[i * 4 + 3] + newLine);
                }
            }
            alarmsWriter.close();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(AlarmsEntryPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedEncodingException ex) {
            Logger.getLogger(AlarmsEntryPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(AlarmsEntryPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_removeButtonActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton removeButton;
    private javax.swing.JLabel timeLabel;
    // End of variables declaration//GEN-END:variables
}
