/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app.monitor;

import app.browser.ExtendedWebBrowser;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.PrintWriter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.SwingUtilities;

/**
 *
 * @author haywoosd
 */
public class StatusMonitorAlertPanel extends javax.swing.JPanel {

    /**
     * Creates new form StatusMonitorAlertPanel
     */
    String labelText;
    String name;
    ExtendedWebBrowser webBrowser;

    public StatusMonitorAlertPanel(String name, String mode, ExtendedWebBrowser webBrowser) {
        this.webBrowser = webBrowser;
        this.name = name;
        labelText = "User " + name + " has been on " + mode + " too long.";
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addSupervisorButton = new javax.swing.JButton();
        dismissButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        addSupervisorButton.setText("Add Supervisor");
        addSupervisorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSupervisorButtonActionPerformed(evt);
            }
        });

        dismissButton.setText("Dismiss");
        dismissButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dismissButtonActionPerformed(evt);
            }
        });

        jLabel1.setText(labelText);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addSupervisorButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                        .addComponent(dismissButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addSupervisorButton)
                    .addComponent(dismissButton))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addSupervisorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSupervisorButtonActionPerformed
        File file = new File(System.getProperty("user.home") + "\\AppData\\Roaming\\SuperToolkit\\Monitor_Settings.txt");
        try {
            PrintWriter write = new PrintWriter(file);
            write.append(name + System.getProperty("line.separator"));
            write.close();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(StatusMonitorAlertPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        webBrowser.updateMonitor();
        SwingUtilities.getRoot(this).setVisible(false);
    }//GEN-LAST:event_addSupervisorButtonActionPerformed

    private void dismissButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dismissButtonActionPerformed
        SwingUtilities.getRoot(this).setVisible(false);
    }//GEN-LAST:event_dismissButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addSupervisorButton;
    private javax.swing.JButton dismissButton;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
