/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app.backup;

import java.io.File;
import java.text.SimpleDateFormat;
import java.util.Arrays;
import java.util.Collections;
import java.util.concurrent.CountDownLatch;

/**
 *
 * @author haywoosd
 */
public class AutoBackupSelectDialog extends javax.swing.JDialog {

    private final String[] fileNames;
    private File selectedFile;
    private final File backupFile;
    private final File[] longTermFileList;
    private final CountDownLatch latch;

    public AutoBackupSelectDialog(java.awt.Frame parent, boolean modal, File backupFile, File longTermBackups, CountDownLatch latch) {
        super(parent, modal);

        this.latch = latch;
        this.backupFile = backupFile;
        longTermFileList = longTermBackups.listFiles();

        SimpleDateFormat sdf = new SimpleDateFormat("MM/dd/yy HH:mm");

        Arrays.sort(longTermFileList);
        Collections.reverse(Arrays.asList(longTermFileList));

        if (backupFile.exists()) {
            fileNames = new String[longTermFileList.length + 1];
            fileNames[0] = sdf.format(backupFile.lastModified()) + " (Latest)";
            for (int i = 0; i < longTermFileList.length; i++) {
                String tempName = longTermFileList[i].getName();
                fileNames[i + 1] = sdf.format(Long.parseLong(tempName.substring(11, tempName.length() - 4)));
            }
        } else {
            fileNames = new String[longTermFileList.length];
            for (int i = 0; i < longTermFileList.length; i++) {
                String tempName = longTermFileList[i].getName();
                fileNames[i] = sdf.format(Long.parseLong(tempName.substring(11, tempName.length() - 4)));
            }
        }

        initComponents();
    }

    public File getSelectedFile() {
        return selectedFile;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        fileSelectBox = new javax.swing.JComboBox(fileNames);
        selectButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Select Backup");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Which backup would you like to load?");

        selectButton.setText("Select");
        selectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(fileSelectBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(selectButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectButton)
                    .addComponent(fileSelectBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void selectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectButtonActionPerformed
        if (backupFile.exists()) {
            if (fileSelectBox.getSelectedIndex() == 0) {
                selectedFile = backupFile;
            } else {
                selectedFile = longTermFileList[fileSelectBox.getSelectedIndex() - 1];
            }
        } else {
            selectedFile = longTermFileList[fileSelectBox.getSelectedIndex()];
        }

        latch.countDown();

        setVisible(false);
    }//GEN-LAST:event_selectButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox fileSelectBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton selectButton;
    // End of variables declaration//GEN-END:variables
}
