/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app.monitor;

import app.browser.ExtendedWebBrowser;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author haywoosd
 */
public class StatusMonitorAlertDialog extends javax.swing.JDialog {

    String labelText;
    String name;
    ExtendedWebBrowser webBrowser;
    
    public StatusMonitorAlertDialog(java.awt.Frame parent, boolean modal, String name, String mode, ExtendedWebBrowser webBrowser) {
        super(parent, modal);
        
        this.webBrowser = webBrowser;
        this.name = name;
        labelText = "User " + name + " has been on " + mode + " too long.";
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addSupervisorButton = new javax.swing.JButton();
        dismissButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Status Monitor");

        addSupervisorButton.setText("Add Supervisor");
        addSupervisorButton.setDefaultCapable(false);
        addSupervisorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSupervisorButtonActionPerformed(evt);
            }
        });

        dismissButton.setText("Dismiss");
        dismissButton.setDefaultCapable(false);
        dismissButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dismissButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText(labelText);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addSupervisorButton)
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(dismissButton))
                    .addComponent(jLabel1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addSupervisorButton)
                    .addComponent(dismissButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addSupervisorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSupervisorButtonActionPerformed
        try {
            File file = new File(System.getProperty("user.home") + "\\AppData\\Roaming\\SuperToolkit\\Monitor_Settings.txt");
            FileWriter write = new FileWriter(file, true);
            write.write(name + System.getProperty("line.separator"));
            write.close();
            webBrowser.updateMonitor();
        } catch (IOException ex) {
            Logger.getLogger(StatusMonitorAlertDialog.class.getName()).log(Level.SEVERE, null, ex);
        }
        setVisible(false);
    }//GEN-LAST:event_addSupervisorButtonActionPerformed

    private void dismissButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dismissButtonActionPerformed
        setVisible(false);
    }//GEN-LAST:event_dismissButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addSupervisorButton;
    private javax.swing.JButton dismissButton;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
